[package]
name = "node-manager"
version = "0.2.2"
edition = "2021"
authors = ["Tony Giorgio <tony@mutinywallet.com>", "benthecarman <ben@mutinywallet.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ln-websocket-proxy = "0.3.0"
lnurl-rs = { version = "0.2", default-features = false, features = ["async", "async-https"] }

cfg-if = "1.0.0"
wasm-bindgen = "0.2.83"
serde-wasm-bindgen = "0.5.0"
bip39 = { version = "1.0.1" }
bip32 = "0.4.0"
bitcoin-bech32 = "0.12"
js-sys = "0.3.60"
secp256k1 = "0.24.0"
bitcoin_hashes = { version = "0.11", default-features = false }
bitcoin = { version = "0.29.2", default-features = false, features = ["serde", "secp-recovery"] }
# TODO waiting for esplora version 0.4.0
bdk = { git = "https://github.com/mutinywallet/bdk", branch = "esplora-tmp", default-features = false, features = ["keys-bip39", "esplora", "use-esplora-reqwest", "async-interface"] }
bdk-macros = "0.6.0"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
gloo-storage = "0.2.2"
rexie = "0.4"
uuid = { version = "1.1.2", features = ["v4"] }
esplora-client = { version = "0.4", default-features = false }
lightning = { version = "0.0.114", default-features = false, features = ["max_level_trace", "grind_signatures", "no-std"] }
lightning-background-processor = { version = "0.0.114", default-features = false, features = ["futures"] }
lightning-invoice = { version = "0.22", default-features = false, features = ["no-std"] }
lightning-rapid-gossip-sync = { version = "0.0.114", default-features = false, features = ["no-std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }
chrono = "0.4.22"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
async-trait = "0.1.60"

base64 = "0.13.0"
pbkdf2 = "0.11"
aes-gcm = "0.10.1"
rand_core = { version = "0.6", features = ["std"] }
crossbeam-channel = "0.5.6"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

wasm-bindgen-futures = "0.4.33"
wasm-logger = "0.2.0"
log = "0.4.17"
gloo-net = "0.2.4"
futures = "0.3.25"
thiserror = "1.0"
web-sys = { version = "0.3.60", features = ["console"] }
anyhow = "1.0"
miniscript = { version = "9.0.0", default-features = false, features = ["no-std"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
mockall = "0.11.2"

[features]
default = ["console_error_panic_hook"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = true

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
