cargo-features = ["per-package-target"]

[package]
name = "mutiny-core"
version = "0.3.5"
edition = "2021"
authors = ["Tony Giorgio <tony@mutinywallet.com>", "benthecarman <ben@mutinywallet.com>"]
forced-target = "wasm32-unknown-unknown"
description = "The core SDK for the mutiny node"
license = "MIT"
documentation = "https://docs.rs/mutiny-core"
homepage = "https://mutinywallet.com"
repository = "https://github.com/mutinywallet/mutiny-node"

[dependencies]
ln-websocket-proxy = "0.3.1"
lnurl-rs = { version = "0.2.4", default-features = false, features = ["async", "async-https"] }

cfg-if = "1.0.0"
wasm-bindgen = "0.2.84"
bip39 = { version = "2.0.0" }
js-sys = { version = "0.3.60", optional = true }
bitcoin = { version = "0.29.2", default-features = false, features = ["serde", "secp-recovery"] }
bdk = { git = "https://github.com/MutinyWallet/bdk.git", branch = "mutiny-no-std", default-features = false }
bdk_esplora = { git = "https://github.com/MutinyWallet/bdk.git", branch = "mutiny-no-std", default-features = false, features = ["async-https"] }
bdk-macros = "0.6.0"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }
uuid = { version = "1.1.2", features = ["v4"] }
esplora-client = { version = "0.4", default-features = false }
lightning = { version = "0.0.115", default-features = false, features = ["max_level_trace", "grind_signatures", "no-std"] }
lightning-invoice = { version = "0.23", default-features = false, features = ["no-std"] }
lightning-rapid-gossip-sync = { version = "0.0.115", default-features = false, features = ["no-std"] }
futures-util = { version = "0.3", default-features = false, features = ["async-await-macro"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }
chrono = "0.4.22"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
async-trait = "0.1.68"
url = { version = "2.3.1", features = ["serde"] }
nostr = { version = "0.22.0-bitcoin-v0.29", default-features = false, features = ["nip47"] }
nostr-sdk = { version = "0.22.0-bitcoin-v0.29", default-features = false }

base64 = "0.13.0"
pbkdf2 = "0.11"
aes-gcm = "0.10.1"
rand_core = { version = "0.6", features = ["std"] }
crossbeam-channel = "0.5.6"

tokio = { version = "1", features = ["rt"], optional = true }

wasm-bindgen-futures = { version = "0.4.33", optional = true }
log = "0.4.17"
gloo-net = "0.2.4"
futures = "0.3.25"
thiserror = "1.0"
web-sys = { version = "0.3.60", features = ["console"], optional = true }
anyhow = "1.0"
miniscript = { version = "9.0.0", default-features = false, features = ["no-std"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
mockall = "0.11.2"

[features]
default = ["async-interface"]
# needed to make async ldk esplora work
async-interface = []
ignored_tests = ["test-utils"]
test-utils = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { version = "0.4.33" }
web-sys = { version = "0.3.60", features = ["console"] }
js-sys = { version = "0.3.60" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
