name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  mutiny-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-10-24
          components: clippy
          targets: wasm32-unknown-unknown

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-release-
            cargo-${{ runner.os }}-

      - name: Cargo Publish
        run: cargo publish -p mutiny-core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}


  mutiny-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-10-24
          components: clippy
          targets: wasm32-unknown-unknown

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-release-
            cargo-${{ runner.os }}-

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.12.1'

      - name: Build wasm
        env:
          RUSTUP_TOOLCHAIN: nightly-2023-10-24
        run: wasm-pack build ./mutiny-wasm --release --weak-refs --target web --scope mutinywallet

      - name: Publish wasm
        run: wasm-pack publish --access public -t web
        env:
          RUSTUP_TOOLCHAIN: nightly-2023-10-24
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
